# Mandatory reading: http://docs.travis-ci.com/user/languages/android/
language: android
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - platform-tools
    # - tools

    # The BuildTools version used by your project
    - build-tools-19.1.0

    # The SDK version used to compile your project
    - android-19

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-19

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-19
    - sys-img-x86-android-17
notifications:
  email:
    recipients:
    # Add your email to be notified if something is committed that can't be compiled
    # Each email on a new line, same indentation as the rest of this block, starting with - (with a space after the dash)
    #EXAMPLE:
  # - you@email.com
    on_success: never
    on_failure: change
